/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class TextEditorProposalProvider extends AbstractTextEditorProposalProvider {
}
