/**
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm;

import fr.ut2j.m1ice.fsm.TextEditorStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TextEditorStandaloneSetup extends TextEditorStandaloneSetupGenerated {
  public static void doSetup() {
    new TextEditorStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
