/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TextEditorGrammarAccess extends AbstractGrammarElementFinder {
	
	public class FSMElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.ut2j.m1ice.fsm.TextEditor.FSM");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFSMKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Assignment cStateAssignment_2_0_0 = (Assignment)cGroup_2_0.eContents().get(0);
		private final RuleCall cStateStateParserRuleCall_2_0_0_0 = (RuleCall)cStateAssignment_2_0_0.eContents().get(0);
		private final Group cGroup_2_0_1 = (Group)cGroup_2_0.eContents().get(1);
		private final Keyword cCommaKeyword_2_0_1_0 = (Keyword)cGroup_2_0_1.eContents().get(0);
		private final Assignment cStateAssignment_2_0_1_1 = (Assignment)cGroup_2_0_1.eContents().get(1);
		private final RuleCall cStateStateParserRuleCall_2_0_1_1_0 = (RuleCall)cStateAssignment_2_0_1_1.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cAlternatives_2.eContents().get(1);
		private final Keyword cTransitionKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cTransitionAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cTransitionTransitionParserRuleCall_2_1_1_0 = (RuleCall)cTransitionAssignment_2_1_1.eContents().get(0);
		private final Group cGroup_2_1_2 = (Group)cGroup_2_1.eContents().get(2);
		private final Keyword cCommaKeyword_2_1_2_0 = (Keyword)cGroup_2_1_2.eContents().get(0);
		private final Assignment cTransitionAssignment_2_1_2_1 = (Assignment)cGroup_2_1_2.eContents().get(1);
		private final RuleCall cTransitionTransitionParserRuleCall_2_1_2_1_0 = (RuleCall)cTransitionAssignment_2_1_2_1.eContents().get(0);
		
		//FSM:
		//	'FSM'
		//	name=EString (state+=State ("," state+=State)* | 'Transition' transition+=Transition ("," transition+=Transition)*)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'FSM' name=EString (state+=State ("," state+=State)* | 'Transition' transition+=Transition (","
		//transition+=Transition)*)*
		public Group getGroup() { return cGroup; }
		
		//'FSM'
		public Keyword getFSMKeyword_0() { return cFSMKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//(state+=State ("," state+=State)* | 'Transition' transition+=Transition ("," transition+=Transition)*)*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//state+=State ("," state+=State)*
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//state+=State
		public Assignment getStateAssignment_2_0_0() { return cStateAssignment_2_0_0; }
		
		//State
		public RuleCall getStateStateParserRuleCall_2_0_0_0() { return cStateStateParserRuleCall_2_0_0_0; }
		
		//("," state+=State)*
		public Group getGroup_2_0_1() { return cGroup_2_0_1; }
		
		//","
		public Keyword getCommaKeyword_2_0_1_0() { return cCommaKeyword_2_0_1_0; }
		
		//state+=State
		public Assignment getStateAssignment_2_0_1_1() { return cStateAssignment_2_0_1_1; }
		
		//State
		public RuleCall getStateStateParserRuleCall_2_0_1_1_0() { return cStateStateParserRuleCall_2_0_1_1_0; }
		
		//'Transition' transition+=Transition ("," transition+=Transition)*
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'Transition'
		public Keyword getTransitionKeyword_2_1_0() { return cTransitionKeyword_2_1_0; }
		
		//transition+=Transition
		public Assignment getTransitionAssignment_2_1_1() { return cTransitionAssignment_2_1_1; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_2_1_1_0() { return cTransitionTransitionParserRuleCall_2_1_1_0; }
		
		//("," transition+=Transition)*
		public Group getGroup_2_1_2() { return cGroup_2_1_2; }
		
		//","
		public Keyword getCommaKeyword_2_1_2_0() { return cCommaKeyword_2_1_2_0; }
		
		//transition+=Transition
		public Assignment getTransitionAssignment_2_1_2_1() { return cTransitionAssignment_2_1_2_1; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_2_1_2_1_0() { return cTransitionTransitionParserRuleCall_2_1_2_1_0; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.ut2j.m1ice.fsm.TextEditor.State");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStateOnParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStateOffParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStateFinalParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//State:
		//	StateOn | StateOff | StateFinal;
		@Override public ParserRule getRule() { return rule; }
		
		//StateOn | StateOff | StateFinal
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StateOn
		public RuleCall getStateOnParserRuleCall_0() { return cStateOnParserRuleCall_0; }
		
		//StateOff
		public RuleCall getStateOffParserRuleCall_1() { return cStateOffParserRuleCall_1; }
		
		//StateFinal
		public RuleCall getStateFinalParserRuleCall_2() { return cStateFinalParserRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.ut2j.m1ice.fsm.TextEditor.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.ut2j.m1ice.fsm.TextEditor.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cSourceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cSourceStateCrossReference_1_0 = (CrossReference)cSourceAssignment_1.eContents().get(0);
		private final RuleCall cSourceStateEStringParserRuleCall_1_0_1 = (RuleCall)cSourceStateCrossReference_1_0.eContents().get(1);
		private final Keyword cSpaceEqualsSignGreaterThanSignSpaceKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTargetAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cTargetStateCrossReference_3_0 = (CrossReference)cTargetAssignment_3.eContents().get(0);
		private final RuleCall cTargetStateEStringParserRuleCall_3_0_1 = (RuleCall)cTargetStateCrossReference_3_0.eContents().get(1);
		
		//Transition:
		//	name=EString
		//	source=[State|EString] ' => ' target=[State|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString source=[State|EString] ' => ' target=[State|EString]
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//source=[State|EString]
		public Assignment getSourceAssignment_1() { return cSourceAssignment_1; }
		
		//[State|EString]
		public CrossReference getSourceStateCrossReference_1_0() { return cSourceStateCrossReference_1_0; }
		
		//EString
		public RuleCall getSourceStateEStringParserRuleCall_1_0_1() { return cSourceStateEStringParserRuleCall_1_0_1; }
		
		//' => '
		public Keyword getSpaceEqualsSignGreaterThanSignSpaceKeyword_2() { return cSpaceEqualsSignGreaterThanSignSpaceKeyword_2; }
		
		//target=[State|EString]
		public Assignment getTargetAssignment_3() { return cTargetAssignment_3; }
		
		//[State|EString]
		public CrossReference getTargetStateCrossReference_3_0() { return cTargetStateCrossReference_3_0; }
		
		//EString
		public RuleCall getTargetStateEStringParserRuleCall_3_0_1() { return cTargetStateEStringParserRuleCall_3_0_1; }
	}
	public class StateOnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.ut2j.m1ice.fsm.TextEditor.StateOn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStateOnAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStateOnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//StateOn:
		//	{StateOn}
		//	'StateOn'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{StateOn} 'StateOn' name=EString
		public Group getGroup() { return cGroup; }
		
		//{StateOn}
		public Action getStateOnAction_0() { return cStateOnAction_0; }
		
		//'StateOn'
		public Keyword getStateOnKeyword_1() { return cStateOnKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class StateOffElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.ut2j.m1ice.fsm.TextEditor.StateOff");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStateOffAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStateOffKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//StateOff:
		//	{StateOff}
		//	'StateOff'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{StateOff} 'StateOff' name=EString
		public Group getGroup() { return cGroup; }
		
		//{StateOff}
		public Action getStateOffAction_0() { return cStateOffAction_0; }
		
		//'StateOff'
		public Keyword getStateOffKeyword_1() { return cStateOffKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class StateFinalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.ut2j.m1ice.fsm.TextEditor.StateFinal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStateFinalAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStateFinalKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//StateFinal:
		//	{StateFinal}
		//	'StateFinal'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{StateFinal} 'StateFinal' name=EString
		public Group getGroup() { return cGroup; }
		
		//{StateFinal}
		public Action getStateFinalAction_0() { return cStateFinalAction_0; }
		
		//'StateFinal'
		public Keyword getStateFinalKeyword_1() { return cStateFinalKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	
	
	private final FSMElements pFSM;
	private final StateElements pState;
	private final EStringElements pEString;
	private final TransitionElements pTransition;
	private final StateOnElements pStateOn;
	private final StateOffElements pStateOff;
	private final StateFinalElements pStateFinal;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TextEditorGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFSM = new FSMElements();
		this.pState = new StateElements();
		this.pEString = new EStringElements();
		this.pTransition = new TransitionElements();
		this.pStateOn = new StateOnElements();
		this.pStateOff = new StateOffElements();
		this.pStateFinal = new StateFinalElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.ut2j.m1ice.fsm.TextEditor".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//FSM:
	//	'FSM'
	//	name=EString (state+=State ("," state+=State)* | 'Transition' transition+=Transition ("," transition+=Transition)*)*;
	public FSMElements getFSMAccess() {
		return pFSM;
	}
	
	public ParserRule getFSMRule() {
		return getFSMAccess().getRule();
	}
	
	//State:
	//	StateOn | StateOff | StateFinal;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Transition:
	//	name=EString
	//	source=[State|EString] ' => ' target=[State|EString];
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//StateOn:
	//	{StateOn}
	//	'StateOn'
	//	name=EString;
	public StateOnElements getStateOnAccess() {
		return pStateOn;
	}
	
	public ParserRule getStateOnRule() {
		return getStateOnAccess().getRule();
	}
	
	//StateOff:
	//	{StateOff}
	//	'StateOff'
	//	name=EString;
	public StateOffElements getStateOffAccess() {
		return pStateOff;
	}
	
	public ParserRule getStateOffRule() {
		return getStateOffAccess().getRule();
	}
	
	//StateFinal:
	//	{StateFinal}
	//	'StateFinal'
	//	name=EString;
	public StateFinalElements getStateFinalAccess() {
		return pStateFinal;
	}
	
	public ParserRule getStateFinalRule() {
		return getStateFinalAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
