/*
 * generated by Xtext 2.14.0
 */
package fr.ut2j.m1ice.fsm.ui;

import com.google.inject.Injector;
import fr.ut2j.m1ice.fsm.TextEditor.ui.internal.TextEditorActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TextEditorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TextEditorActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TextEditorActivator activator = TextEditorActivator.getInstance();
		return activator != null ? activator.getInjector(TextEditorActivator.FR_UT2J_M1ICE_FSM_TEXTEDITOR) : null;
	}

}
